name: Daily YouTube Upload

on:
  schedule:
    # Runs every day at 9:00 AM IST (3:30 AM UTC)
    - cron: '30 3 * * *'
  workflow_dispatch:  # Manual run button

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Run bot
      env:
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
      run: |
        python main.py
